apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
spec:
  selector:
    app: chat
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
spec:
  selector:
    matchLabels:
      app: chat
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: chat
        tier: frontend
        track: stable
    spec:
      containers:
      - name: chat-room-ui
        image: chat-room-ui