apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  selector:
    matchLabels:
      app: chat
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: chat
        tier: backend
        track: stable
    spec:
      containers:
        - name: chat-room-server
          image: chat-room-server
          ports:
            - name: http
              containerPort: 8080